---
- name: Install and Setup Nginx
  hosts: localhost
  become: yes
  tasks:
   - name: Install Nginx
     apt:
       name: nginx
       state: present
       update_cache: yes

   - name: Copy HTML file to Nginx folder
     copy:
       src: ./index.html
       dest: /var/www/html/index.html
       mode: '0644'

   - name: Ensure Nginx is started
     service:
       name: nginx
       state: started
       enabled: yes
